version: "3.8"

services:
  localstack:
    container_name: case-closed-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    environment:
      - SERVICES=sqs,s3,rds,iam,ssm
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/var/lib/localstack
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - SQS_ENDPOINT_STRATEGY=domain
      - SQS_DISABLE_CLOUDWATCH_METRICS=1
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

volumes:
  localstack-data:

networks:
  localstack-network:
    driver: bridge
