export async function up(knex) {
  return knex.raw(`
    CREATE TABLE "orders" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "order_status_id" int NOT NULL,
      "created_at" timestamp NOT NULL,
      "total_cost" float NOT NULL,
      "payment_received" bool NOT NULL DEFAULT false
    );

    CREATE TABLE "order_items" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "order_id" int NOT NULL,
      "quantity" int NOT NULL,
      "case_id" int NOT NULL
    );

    CREATE TABLE "order_statuses" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(32) UNIQUE NOT NULL
    );

    CREATE TABLE "cases" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(32) NOT NULL,
      "price" float NOT NULL,
      "stock_units" int NOT NULL,
      "material_id" int NOT NULL
    );

    CREATE TABLE "materials" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(32) UNIQUE NOT NULL,
      "stock_kg" int NOT NULL
    );

    CREATE TABLE "machinery" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "material_id" int NOT NULL,
      "active" bool NOT NULL DEFAULT true
    );

    CREATE TABLE "incoming_orders" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "order_reference" int NOT NULL,
      "shipment_reference" int,
      "type" VARCHAR(16) NOT NULL,
      "material_id" int,                    
      "quantity_kg" float,                  
      "amount" int,                         
      "ordered_at" timestamp NOT NULL,
      "received_at" timestamp
    );

    ALTER TABLE "orders" ADD FOREIGN KEY ("order_status_id") REFERENCES "order_statuses" ("id");
    ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
    ALTER TABLE "order_items" ADD FOREIGN KEY ("case_id") REFERENCES "cases" ("id");
    ALTER TABLE "cases" ADD FOREIGN KEY ("material_id") REFERENCES "materials" ("id");
    ALTER TABLE "machinery" ADD FOREIGN KEY ("material_id") REFERENCES "materials" ("id");
    ALTER TABLE "incoming_orders" ADD FOREIGN KEY ("material_id") REFERENCES "materials" ("id");

  `);
}

export async function down(knex) {
  return knex.raw(`
    DROP TABLE IF EXISTS "incoming_orders" CASCADE;
    DROP TABLE IF EXISTS "order_items" CASCADE;
    DROP TABLE IF EXISTS "machinery" CASCADE;
    DROP TABLE IF EXISTS "cases" CASCADE;
    DROP TABLE IF EXISTS "materials" CASCADE;
    DROP TABLE IF EXISTS "orders" CASCADE;
    DROP TABLE IF EXISTS "order_statuses" CASCADE;
  `);
}