export async function up(knex) {
  return knex.raw(`
    CREATE TABLE "case_orders" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "order_status_id" int NOT NULL,
      "quantity" int NOT NULL,
      "total_price" float NOT NULL,
      "ordered_at" timestamp NOT NULL
    );

    CREATE TABLE "order_statuses" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(32) UNIQUE NOT NULL
    );

    CREATE TABLE "stock" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "stock_type_id" int NOT NULL,
      "total_units" int NOT NULL
    );

    CREATE TABLE "stock_types" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(32) UNIQUE NOT NULL
    );

    CREATE TABLE "external_orders" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "order_reference" varchar(255) UNIQUE NOT NULL,
      "total_cost" float NOT NULL,
      "order_type_id" int NOT NULL,
      "shipment_reference" varchar(255),
      "ordered_at" timestamp NOT NULL,
      "received_at" timestamp
    );

    CREATE TABLE "order_types" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(32) UNIQUE NOT NULL
    );

    CREATE TABLE "external_order_items" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "stock_type_id" int NOT NULL,
      "order_id" int NOT NULL,
      "ordered_units" int NOT NULL,
      "per_unit_cost" float NOT NULL
    );

    ALTER TABLE "case_orders" 
      ADD FOREIGN KEY ("order_status_id") REFERENCES "order_statuses" ("id");

    ALTER TABLE "stock" 
      ADD FOREIGN KEY ("stock_type_id") REFERENCES "stock_types" ("id");

    ALTER TABLE "external_orders" 
      ADD FOREIGN KEY ("order_type_id") REFERENCES "order_types" ("id");

    ALTER TABLE "external_order_items" 
      ADD FOREIGN KEY ("stock_type_id") REFERENCES "stock_types" ("id");

    ALTER TABLE "external_order_items" 
      ADD FOREIGN KEY ("order_id") REFERENCES "external_orders" ("id");
  `);
}

export async function down(knex) {
  return knex.raw(`
    DROP TABLE IF EXISTS "external_order_items" CASCADE;
    DROP TABLE IF EXISTS "external_orders" CASCADE;
    DROP TABLE IF EXISTS "order_types" CASCADE;
    DROP TABLE IF EXISTS "stock" CASCADE;
    DROP TABLE IF EXISTS "stock_types" CASCADE;
    DROP TABLE IF EXISTS "case_orders" CASCADE;
    DROP TABLE IF EXISTS "order_statuses" CASCADE;
  `);
}