name: Deployment Certs
env:
  AWS_REGION: af-south-1

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # === Code Checkout ===
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Parameters
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

        
     # === Package Deployment Artifacts ===


      - name: Get SSL Certs from SSM
        run: |
            mkdir -p ./tmp
            aws ssm get-parameter --name "/ssl/crt" --query "Parameter.Value" --output text > ./tmp/ssl_cert.crt
            aws ssm get-parameter --name "/ssl/privkey_pem" --query "Parameter.Value" --output text > ./tmp/ssl_key.pem

      - name: Create Deployment Package
        run: |
            tar -czf ./certs.tar.gz -C ./tmp .


          
      # === Transfer Package to EC2 ===
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 13.246.82.211
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "certs.tar.gz"
          target: "/home/ec2-user/"
      
      
      
            # === Deploy on EC2 ===
    #   - name: Upload SSL Certs and Configure Nginx
    #     uses: appleboy/ssh-action@v1.0.0
    #     with:
    #         host: 13.246.82.211
    #         username: ${{ secrets.EC2_USER }}
    #         key: ${{ secrets.EC2_SSH_KEY }}
    #         port: 22
    #         script: |
    #             set -e        
    #             sudo mkdir -p /etc/ssl/casesupplier/

    #             sudo bash -c "cat > /etc/ssl/casesupplier/casesupplier_cert.crt" << EOF
    #             ${{ steps.ssm.outputs.ssl_cert }}
    #             EOF

    #             sudo bash -c "cat > /etc/ssl/casesupplier/casesupplier_key.pem" << EOF
    #             ${{ steps.ssm.outputs.ssl_key }}
    #             EOF

    #             sudo chmod 644 /etc/ssl/casesupplier/casesupplier_cert.crt
    #             sudo chmod 600 /etc/ssl/casesupplier/casesupplier_key.pem

            
